name: first

on: 
  push:
      branches: 
          - master
          - develop

jobs:
    job4:
        name: fourth one
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: env | sort
    job3:
        name: third
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: env | sort
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: env | sort
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: "Get-ChildItem Env: | Sort-Object Name"
    independentJobTwo:
      name: Independent Job two
      runs-on: ubuntu-latest
      steps:
          - name: Step one
            uses: actions/checkout@v2
          - name: Step two
            run: env
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: "Get-ChildItem Env: | Sort-Object Name"
    independentJob:
        name: independent Job one
        runs-on: windows-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: "Get-ChildItem Env: | Sort-Object Name"
    depends:
        name: depends Job
        needs: [job1, job2]
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: ls
    dependtwo:
        name: depends on one and four
        needs: [job1, job3]
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: ls
    dependthree:
        name: depends on one and four
        needs: [job3, job4]
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: ls
